<?
$PSE_LANG = array(
'descr_id' => '',
'descr_parent'		=> 'Родительская категория',
'descr_page'		=> 'Ссылка на страницу',
'descr_name'		=> 'Название',
'descr_title'		=> 'TITLE',
'descr_description'	=> 'Meta DESCRIPTION',
'descr_keywords'	=> 'Meta KEYWORDS',
'descr_text'		=> 'Содержание',
'descr_date'		=> 'Дата (ГГГГ-ММ-ДД)',
'descr_display'		=> 'Отображать на сайте',
'descr_constant'	=> 'Константа',
'descr_short_text'	=> 'Краткое описание',
'descr_position'	=> 'Позиция в списке',
'descr_pass'		=> 'Пароль',
'descr_pic'			=> 'Изображение/Фото',
'descr_video'		=> 'Видео файл',
'descr_path'		=> 'Файл',
'descr_work_type'		=> 'Тип работ',
'descr_sname'		=> 'Имя',
'descr_age'		=> 'Возраст',
'descr_autotext'		=> '<b style="color:red;">Бегущая строка</b>',
'descr_shedule'		=> 'График работ',
'descr_nationality'		=> 'Начиональность',
'descr_citizenship'		=> 'Гражданство',
'descr_education'		=> 'Образование',
'descr_speciality'		=> 'Специальность',
'descr_exp'		=> 'Опыт работы',
'descr_skills'		=> 'Проффесиональные навыки',
'descr_additional'		=> 'Дополнительно',
'descr_tag_enable'		=> 'Разрешить тэги',
'descr_file'		=> 'Файл',
'descr_rights'		=> '',
'descr_topic'		=> 'Топик',
'SAVE'				=> 'Сохранить',
'CANCEL' 			=> 'Отмена',
'DELETE' 			=> 'Удалить',
'SUB_TEMPLATE' 		=> 'запись',
);
$PSE_SYS_LANG = array(
'items' => 'Статьи',
'units' => 'Персонал',
'photos' => 'Фото',
'files' => 'Файлы',
'comments' => 'Комментарии'
);
?>